#!/usr/bin/with-contenv bash

# Fetch site or update existing
if [[ ! -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '| Installing Organizr |'
  echo '-----------------------'
  git clone -b v2-master https://github.com/causefx/Organizr /config/www/Dashboard
elif [[ -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Organizr  |'
  echo '-----------------------'
  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
  git fetch
  git reset --hard origin/v2-master
  git checkout v2-master
  git reset --hard origin/v2-master
  git pull
fi

# Make sure the config.php file is using the correct branch
sed -i "s/'branch' => '[^']*',/'branch' =\> 'v2-master',/" /config/www/Dashboard/api/config/config.php

# Set Permissions
chown -R abc:abc \
	/config
