#!/usr/bin/with-contenv bash

# Fetch site or update existing
if [[ ! -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '| Installing Organizr |'
  echo '-----------------------'
  git clone -b v2-develop https://github.com/causefx/Organizr /config/www/Dashboard
  git rev-parse HEAD > /config/www/Dashboard/Github.txt
elif [[ -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Organizr  |'
  echo '-----------------------'
  cd /config/www/Dashboard || (echo 'Failed to load Organizr repository folder'; exit)
  git fetch
  git reset --hard origin/v2-develop
  git checkout v2-develop
  git reset --hard origin/v2-develop
  git pull
  git rev-parse HEAD > /config/www/Dashboard/Github.txt
fi

# Copy over Nginx status config file if it doesn't exist
if [ ! -f /config/nginx/site-confs/healthcheck.conf ]; then
  echo '----------------------------------'
  echo '| Copying Nginx status conf file |'
  echo '----------------------------------'
  cp /defaults/healthcheck.conf /config/nginx/healthcheck.conf
else
  :
fi

# Check for the include for the healthcheck conf and,
# if it does not exist, add it
if [[ $(grep -c healthcheck /config/nginx/site-confs/default) -eq 0 ]]; then
  sed -i $'s|root /config/www/Dashboard;|root /config/www/Dashboard;\\\n        include /config/nginx/healthcheck.conf;|g' /config/nginx/site-confs/default
elif [[ $(grep -c healthcheck /config/nginx/site-confs/default) -ge 1 ]]; then
  :
fi

# Set Permissions
chown -R abc:abc \
	/config
