#!/usr/bin/with-contenv bash

# Changes to work with Plex Theme
echo '------------------------------------'
echo '| Making JS changes for Plex Theme |'
echo '------------------------------------'
sed -ie 's;i=40;i=60;g' /config/www/Dashboard/js/custom.min.js
