#!/usr/bin/with-contenv bash

# Changes to work with Plex Theme
echo '------------------------------------'
echo '| Making JS changes for Plex Theme |'
echo '------------------------------------'
sed -ie 's;h=40;h=60;g' /config/www/Dashboard/js/custom.min.js
sed -i '278i\                        $('\''.sidebar'\'').addClass('\''hidden'\'');' /config/www/Dashboard/js/functions.js
sed -i '279i\                        $('\''.navbar'\'').addClass('\''hidden'\'');' /config/www/Dashboard/js/functions.js
sed -i '280i\                        $('\''#pagewrapper'\'').addClass('\''hidden'\'');' /config/www/Dashboard/js/functions.js

# Edit www.conf file for PHP-FPM
echo '-----------------------'
echo '| Configuring PHP-FPM |'
echo '-----------------------'
echo "[www]" > /config/php/www.conf
echo "user = abc" >> /config/php/www.conf
echo "group = abc" >> /config/php/www.conf
echo "listen = '/var/run/php7-fpm.sock'" >> /config/php/www.conf
echo "listen.owner = abc" >> /config/php/www.conf
echo "listen.group = abc" >> /config/php/www.conf
echo "listen.mode = 0660" >> /config/php/www.conf
echo "pm = ondemand" >> /config/php/www.conf
echo "pm.max_children = 4000" >> /config/php/www.conf
echo "pm.start_servers = 2" >> /config/php/www.conf
echo "pm.min_spare_servers = 1" >> /config/php/www.conf
echo "pm.max_spare_servers = 3" >> /config/php/www.conf
echo "pm.process_idle_timeout = 10s;" >> /config/php/www.conf
echo "pm.max_requests = 0" >> /config/php/www.conf

# Set Permissions
chown -R abc:abc \
	/config/php/www.conf
