#!/usr/bin/with-contenv bash

# Backup the www.conf file for PHP-FPM if it exists
# & copy in www.conf for PHP-FPM
if [ ! -f /config/php/www.conf.original ]; then
  echo '---------------------------'
  echo '| Backing up www.conf file |'
  echo '---------------------------'
  mv /config/php/www.conf /config/php/www.conf.original
  echo '---------------------------'
  echo '|  Copying www.conf file  |'
  echo '---------------------------'
  cp /defaults/www.conf /config/php/www.conf
elif [[ ! -f /config/php/www.conf ]]; then
  cp /defaults/www.conf /config/php/www.conf
fi

# Set Permissions
chown -R abc:abc \
	/config
